### ISSUE TITLE
FARM

### ISSUE THREAD

**Issue by dwincort** [cdsmith/voronoizer#1]
This isn't an issue, exactly, but after reading your extensive medium post about voronoizer, it made me think this could be a good demo for FARM (https://functional-art.org).  (Full disclosure, I've run FARM in the past and am currently on the PC.)  The submission deadline has passed for this year, but you could try contacting the Chairs and seeing if you could submit late.  Or, perhaps FARM 2024?

**Comment by cdsmith** [comment]
Thanks for the recommendation!  Indeed, I've attended FARM in the past, and it would be interesting to speak there.  I think it would require a higher level of sophistication than my weekend project, but I'm still interested in continuing to develop this as free time allows, and I hope to eventually reach the point where there's a more complete story worth telling in such a forum.  FARM 2024 would definitely be an interesting possibility.
